### ISSUE TITLE
projects up for adoption

### ISSUE THREAD

**Issue by kohlhase** [KWARC/kwarc.info#6]
I would like to have a category of projects that are up for adoption (still relevant, but we need people who do the work). 
I think we can just add a new keyword `adoption` in the header that generates a highlighted `this project is up for adoption` and we have a new subpage `up for adoption` of these projects. 
We can then rename the subpage `current projects` to `active projects`.

**Comment by kohlhase** [comment]
We should also use the `adoption` projects  in the possible theses section. 
The subpages should have text that explains the status and cross-links.

**Comment by tkw1536** [comment]
migrated to gitlab, closing
